# Generated by Django 3.1.3 on 2020-11-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pescaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(verbose_name='date published')),
                ('members', models.ManyToManyField(to='pescaria.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Peixe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pescaria.pescaria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pescaria.usuario')),
            ],
        ),
    ]
